Repository camedomotic-unofficial/came_domotic_unofficial, pull requests merged in 2024-03, with the labels that each got.

#1 Updated sphinx documentation
  README.md
  README.rst
  docs/source/conf.py
  docs/source/index.rst
Labels: documentation

#2 Update project metadata and URLs
  pyproject.toml
Labels: chore

#3 Update documentation
  README.rst
  docs/source/usage_examples.rst
  tests/came_etidomo_server/test_docs_snippets.py
Labels: documentation

#4 Update Codecov action and versioning management workflow
  .github/workflows/check_code.yml
  .github/workflows/versioning_management.yml
Labels: chore

#5 Update Codecov action and versioning management workflow
  .github/workflows/versioning_management.yml
Labels: chore

#6 Add RTD build docs action
  .github/workflows/check_security.yml
  .github/workflows/check_security_scheduled.yml
  .github/workflows/docs.yml
  .github/workflows/release_drafter.yml
  .github/workflows/repository_maintenance.yml
  .github/workflows/versioning_management.yml
  docs/source/requirements.in
  docs/source/requirements.txt
Labels: chore

#7 Update Sphinx configuration path and requirements file
  .github/workflows/docs.yml
  .readthedocs.yaml
Labels: documentation

#8 Fixed SonarQube evidences
  .github/workflows/code-quality.yml
  README.rst
  came_domotic_unofficial/came_etidomo_server.py
  came_domotic_unofficial/models/enums.py
  came_domotic_unofficial/models/light.py
  tests/came_etidomo_server/test_internal_automatic_login.py
  tests/came_etidomo_server/test_properties.py
  tests/came_etidomo_server/test_public_methods.py
  tests/came_etidomo_server/test_special_methods.py
  tests/came_etidomo_server/utils.py
  tests/models/test_cameentity.py
Labels: bug, chore

#9 Switched to poetry and updated actions
  .github/workflows/build_publish_test.yml
  .github/workflows/check_code.yml
  .github/workflows/code-quality.yml
  .github/workflows/code-tests.yml
  CONTRIBUTING.md
  README.rst
  pyproject.toml
  requirements.txt
  sonar-project.properties
Labels: documentation, chore

#10 Update badges in README.rst
  README.rst
Labels: documentation

#11 Refactored the build and publish workflow
  .github/workflows/build-publish.yml
  .github/workflows/build_publish_test.yml
  .github/workflows/code-quality.yml
  .github/workflows/code-tests.yml
  requirements.txt
Labels: chore

#12 Added versioning strategy
  CONTRIBUTING.md
  README.rst
  pyproject.toml
Labels: documentation, chore

#13 Add version update and publishing options to build workflow
  .github/workflows/build-publish.yml
Labels: chore

#14 Remove outdated security check workflows and add new consolidated security workflow
  .github/workflows/check_security_scheduled.yml
  .github/workflows/repository-maintenance.yml
  .github/workflows/repository_maintenance.yml
  .github/workflows/security.yml
  .github/workflows/versioning_management.yml
Labels: chore
